// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLHIAPSlWZlUddivv0pnSkzZBbql_qy1o',
    appId: '1:183587622641:web:3d65096cdf7effdff86350',
    messagingSenderId: '183587622641',
    projectId: 'thebanyette',
    authDomain: 'thebanyette.firebaseapp.com',
    storageBucket: 'thebanyette.appspot.com',
    measurementId: 'G-SE0Y1G6RHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29lvrCSfaNByMgg7pBod2a8qIZOcaxUM',
    appId: '1:183587622641:android:483998899d6bc929f86350',
    messagingSenderId: '183587622641',
    projectId: 'thebanyette',
    storageBucket: 'thebanyette.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOwtGja84hAz-dqWdiR9Z5KJLykF0THLo',
    appId: '1:183587622641:ios:c464c1e5b4180c82f86350',
    messagingSenderId: '183587622641',
    projectId: 'thebanyette',
    storageBucket: 'thebanyette.appspot.com',
    iosClientId: '183587622641-l1dcf6bitsqcdn6t3mbfk7nc1gta098b.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBanyette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOwtGja84hAz-dqWdiR9Z5KJLykF0THLo',
    appId: '1:183587622641:ios:c464c1e5b4180c82f86350',
    messagingSenderId: '183587622641',
    projectId: 'thebanyette',
    storageBucket: 'thebanyette.appspot.com',
    iosClientId: '183587622641-l1dcf6bitsqcdn6t3mbfk7nc1gta098b.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBanyette',
  );
}
